### ISSUE TITLE
Does not work with messages editing.

### ISSUE THREAD

**Issue by tmartincpp** [zakhar-petrov/rocketchat-youtrack-linker#11]
Hello,

I'm not able to make this app works when I edit a message while I don't have any issue if I directly write a message with the pattern.

As a example: 
1. Working scenario : 
  1.1 write a message with a pattern 
`Please see YT-5757`
  1.2 It works, pattern will be substitute by HTTP link (according to the app configuration)

2. Not working : 
  2.1 write a message but forgot the pattern
`Please see`  
  2.2 edit this message and add _YT-5757_
 `Please see YT-5757`
  2.3 This will result in a message with text only, pattern will not by substitute.

Any chance to make it work with messages editing ?

Thanks.

**Comment by Zakhar-Petrov** [comment]
Hi @tmartincpp, thank you for the issue that you raised!

> Any chance to make it work with messages editing ?

I think it's possible with [IPreMessageUpdatedModify](https://rocketchat.github.io/Rocket.Chat.Apps-engine/interfaces/messages_ipremessageupdatedmodify.ipremessageupdatedmodify.html) interface. I'll check it.

**Comment by Zakhar-Petrov** [comment]
Hi, @tmartincpp!

Seems I fixed it. New version is not published yet but you can try to upload it from [release assets](https://github.com/zakhar-petrov/rocketchat-youtrack-linker/releases/tag/v1.2.1) to your RocketChat server.

**Comment by tmartincpp** [comment]
Hi @zakhar-petrov.
Thanks a lot !
it seems to work perfectly :+1: !
