### ISSUE TITLE
Linker works for joined issue reference text

### ISSUE THREAD

**Issue by Zakhar-Petrov** [zakhar-petrov/rocketchat-youtrack-linker#5]
Default issue pattern links following text lines:
- **ACM-123ABC-123**
- 0**ABC-123**
- **ABC-123**A

Seems, it should ignore such lines

Sugession for regex pattern: `(^|[^a-zA-Z0-9])([a-zA-Z]+-[0-9]+)([^a-zA-Z0-9]|$)` instead of `[a-zA-Z]+-[0-9]+`

**Comment by weizenspreu** [comment]
We had the exact same issue (e.g. in situations like "abc123-456**def-789**ghi-jkl") but found that the app doesn't care for non-capturing groups or capture groups in general. Therefore we created this alternative regex which uses non-capturing look-behind and look-ahead groups and makes it possible to have certain special characters lead or trail the issue ID:

```
(?<=^|\s|\,|\;|\:|\.|\!|\?)[a-zA-Z]+-[0-9]+(?=$|\s|\,|\;|\:|\.|\!|\?)
```

**Comment by Zakhar-Petrov** [comment]
> We had the exact same issue (e.g. in situations like "abc123-456**def-789**ghi-jkl") but found that the app doesn't care for non-capturing groups or capture groups in general. Therefore we created this alternative regex which uses non-capturing look-behind and look-ahead groups and makes it possible to have certain special characters lead or trail the issue ID:
> 
> ```
> (?<=^|\s|\,|\;|\:|\.|\!|\?)[a-zA-Z]+-[0-9]+(?=$|\s|\,|\;|\:|\.|\!|\?)
> ```

Hi @yahesh! Thanks for your solution, regex lookaround is exactly what fixed the problem!

I've added lookbehind `(?<=^|[^a-zA-Z0-9])` and lookaround `(?=[^a-zA-Z0-9]|$)` to issue pattern.

Also exclude pattern was added for markdown link like `[...](https://...)`.
